services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: monbondocteur
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - monbondocteur-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monbondocteur_app
    depends_on:
      - db
    ports:
      - "9080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/monbondocteur
    networks:
      - monbondocteur-net

volumes:
  db-data:

networks:
  monbondocteur-net:
